export const PRODUCTS_LIST_REQUEST="PRODUCTS_LIST_REQUEST";
export const PRODUCTS_LIST_SUCCES="PRODUCTS_LIST_SUCCES";
export const PRODUCTS_LIST_FAIL="PRODUCTS_LIST_FAIL";


export const PRODUCT_DETAILS_REQUEST="PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_SUCCES="PRODUCT_DETAILS_SUCCES";
export const PRODUCT_DETAILS_FAIL="PRODUCT_DETAILS_FAIL";